export const types = {
  LOADING: "LOADING",

  LOAD_FOODS: "LOAD_FOODS",
  LOAD_FOODS_SUCCESS: "LOAD_FOODS_SUCCESS",
  LOAD_FOODS_ERROR: "LOAD_FOODS_ERROR",

  LOAD_FOOD: "LOAD_FOOD",
  LOAD_FOOD_SUCCESS: "LOAD_FOOD_SUCCESS",
  LOAD_FOOD_ERROR: "LOAD_FOOD_ERROR",
};
